name: Backend deployment workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


permissions:
  id-token: write   # required for OIDC
  contents: read
  pull-requests: write


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
           working-directory: backend

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

        env:
          REDIS_URL: redis://localhost:6379
          NODE_ENV: test
          RATE_LIMIT_REGISTER: 5   
          RATE_LIMIT_LOGIN: 10      
          RATE_LIMIT_REDIRECT: 60

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest

        - name: Install dependencies
          run: bun install --frozen-lockfile

        - name: Type check
          run: bun tsc --noEmit

        - name: Run tests
          run: bun test --coverage

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    env:
      AWS_REGION: ${{secrets.REGION}}
      ECR_REPOSITORY: ${{secrets.AWS_REPOSITORY}} 

    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate image metadata
        id: meta
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          SHORT_SHA=${GITHUB_SHA::7}
          IMAGE_TAG=${GITHUB_REF_NAME}-${SHORT_SHA}
          IMAGE_URI=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
          echo "registry=$ECR_REGISTRY" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ steps.meta.outputs.image_uri }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_SHA=${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    env:
      AWS_REGION: ${{secrets.REGION }} 
      AWS_PROJECT:  ${{secrets.AWS_PROJECT}}  
      ECR_REPOSITORY: ${{secrets.AWS_REPOSITORY}} 
  

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{ env.AWS_REGION }}


      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition "${{ env.AWS_PROJECT }}-api" \
            --query taskDefinition \
            > task-definition.json | jq 'del(
                .taskDefinitionArn,
                .revision,
                .status,
                .requiresAttributes,
                .compatibilities,
                .registeredAt,
                .registeredBy,
                .containerDefinitions[].restartPolicy,
                .containerDefinitions[].versionConsistency
              )' \
            > task-definition.json


      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Get image digest
        id: digest
        run: |
          DIGEST=$(aws ecr describe-images \
            --repository-name ${{ env.ECR_REPOSITORY }} \
            --image-ids imageTag=${{ needs.build-and-push.outputs.image_tag }} \
            --query 'imageDetails[0].imageDigest' \
            --output text)

           IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}@${DIGEST}"
           echo "uri=$IMAGE_URI" >> $GITHUB_OUTPUT
  
      - name: Update image in task definition
        id: update-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1.8.0
        with:
          task-definition: task-definition.json
          container-name: "${{ env.AWS_PROJECT }}-api"
          image: ${{ steps.image.outputs.uri }} 

      - name: Deploy to ECS
        id: deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.update-task-def.outputs.task-definition }}
          service: "${{ env.AWS_PROJECT }}-api"
          cluster: "${{ env.AWS_PROJECT }}-cluster"
          wait-for-service-stability: true
          wait-for-minutes: 10
